declare const EmptyStr = "";
declare const ERR_STR_MISSING_Q = 1;
declare const ERR_ILLEGAL_NUMBER = 2;
declare const ERR_ILLEGAL_CHAR = 3;
declare const ERR_INVALID_NAME = 4;
declare const ERR_INVALID_REF = 5;
declare const ERR_QUOTED_NAME_MISSING_Q = 6;
declare const REGX_NAME_CHAR: RegExp;
declare const ERROR_FORMULA_STR = "The formula is incorrect";
export { EmptyStr, ERR_STR_MISSING_Q, ERR_ILLEGAL_NUMBER, ERR_ILLEGAL_CHAR, ERR_INVALID_NAME, ERR_INVALID_REF, ERR_QUOTED_NAME_MISSING_Q, REGX_NAME_CHAR, ERROR_FORMULA_STR, };
